### ISSUE TITLE
CSV File save path_issue

### ISSUE THREAD

**Issue by tajmulalam** [hsmnzaydn/easy-csv#1]
Thanks dude for your library. Can u tell me how can i configure the csv file saving path??. i need to save it in a specific folder. Thanks in advanced

**Comment by endlesstech** [comment]
Yes, I faced the same issue. It is saved in the SD card.

**Comment by endlesstech** [comment]
I created a new EasyCsv class. I change File path to both SD and Internal storage path in this line 
 this.file = new File(Environment.getExternalStorageDirectory() + File.separator + fileName + ".csv");
with 
  this.file = new File(getRootDirPath(activity) + File.separator + fileName + ".csv");

public String getRootDirPath(Context context) {
        if (Environment.MEDIA_MOUNTED.equals(Environment.getExternalStorageState())) {
            File file = ContextCompat.getExternalFilesDirs(context.getApplicationContext(),
                    null)[0];
            return file.getAbsolutePath();
        } else {
            return context.getApplicationContext().getFilesDir().getAbsolutePath();
        }
    }
